<?
$PERM["styles___"]["5"]="X";
$PERM["sprite___"]["5"]="X";
$PERM["scripts___"]["5"]="X";
$PERM["images___"]["5"]="X";
$PERM["fonts___"]["5"]="X";
$PERM["styles.css"]["5"]="X";
$PERM["favicon.ico"]["5"]="X";
$PERM[".DS_Store"]["5"]="X";
$PERM["description.php"]["5"]="X";
$PERM["snippets"]["5"]="X";
$PERM["include_areas"]["5"]="X";
?>